name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        run: |
          npm install
      - name: Generate GitHub Profile 3D Contribution Graph
        run: |
          npx github-profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions[bot]@users.noreply.github.com
          git add -A .
          if git commit -m "generated"; then
            git push
          fi
